### ISSUE TITLE
[Enhancement] MMOCore and RPGInventory support

### ISSUE THREAD

**Issue by ThePhoenix96** [Eredrim/pvparena#118]
please add MMOCore and RPGInventory support. 

would be nice to see MMOItems support for kits too.

**Comment by Eredrim** [comment]
Hi, sorry for the late answer.

PVP Arena is designed to offer a dedicated PVP instance, separated of all the server content. It brings its own class management, death management, exp management, etc. So, integration role-play plugin feature is still complicated because it just at the opposite of our philosophy.
However, in its current version, the plugin is quite flexible with custom content and they are often some tips to make compatible several of external plugin features. The first one is to use the "[classchest](https://github.com/Eredrim/pvparena/blob/master/doc/commands/classchest.md)" feature, that uses game items as-is. So if you have items with special powers or attributes that don't work with normal class feature (i.e. serialized in arena config file), I suggest to use this feature.
The second one consists to use the "[eventactions](https://github.com/Eredrim/pvparena/blob/master/doc/mods/eventactions.md)" modules and/or command block. They make possible to call any commands at key moments of the game (kill, death, win, etc) or more easily with redstone on your battleground.

**Comment by ThePhoenix96** [comment]
okay and how about RPGInventory support ?

**Comment by Eredrim** [comment]
RPGInventory is a too much specific plugin and doesn't have any API. Normally, you'll still be able to use main part of inventory with PVP Arena but special slots won't work (you can give it a try but I don't think so).

**Comment by ThePhoenix96** [comment]
ye it doesn't works, that's why i am here. :(
