### ISSUE TITLE
maxhealth arena config setting damaging players on arena join

### ISSUE THREAD

**Issue by Poffers** [Eredrim/pvparena#18]
The `maxhealth` arena config setting seems to have strange results. Players' max health is correctly set, but any value below 20 will also damage players on arena join. Even worse, it seems that the lower the number, the more damage they take. A value of 10 or below will kill players instantly on join, and it's impossible to click respawn. The only real way out is to go back to the title screen or close the game.

It's important to note that the first player that joins the arena doesn't take any damage. Only every player that joins after them.

(Using build 316)

**Comment by Eredrim** [comment]
Hello,

did you also set the "health" value to the same value than "maxHealth" ? If yes, what server version are you using ? (craftbukkit, spigot, paper)

**Comment by Poffers** [comment]
I was using -1 as the `health` value, but setting it to the same as `maxhealth` still has the same result.

However, setting it lower than the maxhealth (Example: health is 4 and maxhealth is 10) still kills them but then sets their health correctly. They're able to click respawn once and move just fine.

I've also just noticed that when they are killed, they never actually disappear like a typical death, and are actually still visible at the lounge spawn.

I'm using Paper 1.14.4 build 152

**Comment by Eredrim** [comment]
I confirm the issue. I was able to reproduce it. I will fix it ASAP.

**Comment by Eredrim** [comment]
I am currently stuck on this issue. The problem seems to be partially linked to spigot 1.14 but I didn't found anything to resolve it.
Concretely, after all of the lounge joining code was executed, something like an event remove `20 - maxPlayerHealth` to the player.

A workaround consists to set the `health` property 1 point below the the `maxHealth` property.

I asked some help to another developer and I continue to look for a solution.

**Comment by Eredrim** [comment]
I finally succeed at fixing it. The patch is present in dev build #317 and after.
