### ISSUE TITLE
Possibility to avoid respawning with death screen

### ISSUE THREAD

**Issue by Eredrim** [Eredrim/pvparena#36]
Forked from #25 
> By spam clicking and assumed being able to click the respawn screen before PVPArena hides it, players are able to respawn exactly where they died if they have multiple lives. Basically cancelling any teleport events the arena is trying to handle (i.e. respawn in spawn locations or respawn in spectator location).

**Comment by Eredrim** [comment]
Hi,
I think I managed to fix it. Can you try latest 1.15.0 snapshot to confirm all works ?

**Comment by mibby** [comment]
@Eredrim Compiled as of commit https://github.com/Eredrim/pvparena/commit/568dbe89e261cf7316d252995b8a10e15ceaf772

Had some testers try to reproduce with the latest development branch. The respawn glitch isn't completely fixed, but it is way better. Not as consistent as before but still happens.

**Comment by Eredrim** [comment]
Sincerely it will be difficult to do better. Death screen now appears for 1 tick (50ms) and this tick is mandatory since player dies. Of my side of things, I am just able to catch sight of it and respawn buttons still disable. So I don't understand how your players do...
The last option I may have would be to bypass minecraft death and calculate when death will happen with damages. But this method is very unpredictable and may have huge side effects.

**Comment by mibby** [comment]
What about optionally soft depend on ProtocolLib if it exists and use packets to catch the death screen?

**Comment by Eredrim** [comment]
I don't want to use protocollib because it's a labyrinth (from my point of view) and it's too version dependent.
To answer to the "why" question. I sincerely don't know. You're the only person who have the bug and I never had success to reproduce it (despite tens of tries). There is no event sent by death screen or anything else that can logically stop teleportation.

**Comment by mibby** [comment]
I tried to reproduce the respawning in same death spot issue in 5 different duel games back-to-back but could not get it to happen myself, whereas I was able to with older dev builds. I'm under the assumption the issue is properly fixed as of commit https://github.com/Eredrim/pvparena/commit/7beea5ce40fe33df73702bafa193eb1f92c195a6 or a newer Paper upstream change resolved whatever was the cause.

I'm going to have the players who initially reported it was still occurring (but significantly less) try to reproduce it again and if they can, then I'll create a minimal environment to see if it can be reproduced with nothing else going on. 

If they can't reproduce again, assuming fixed. :)

**Comment by Eredrim** [comment]
Hi @mibby !
Do you have any news about this ?

**Comment by mibby** [comment]
I could not reproduce this and haven't heard any complaints since it was fixed, so assume it is no longer an issue. If I hear anything new, I'll re-open a new ticket with some debug reproduction. Otherwise this can probably be closed.

**Comment by Eredrim** [comment]
Ok, thank you very much.
