### ISSUE TITLE
Reloading specific arenas does not reload the class chest contents.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#37]
PVPArena dev 319

If you reload a specific arena with ``/pa <arena> reload``, the class chest location contents do not get refreshed. You have to join the arena, play in it, then have it end to refresh.

However if you reload with ``/pa reload``, the chest contents do seem to get reloaded.

**Comment by Eredrim** [comment]
I'm not sure to correctly understand the problem. You talking about the [classchest](https://github.com/Eredrim/pvparena/blob/master/doc/commands/classchest.md) command, right ?
If so, a chest contains items which replace class items defined in your arena config file. Therefore you set chest location with command `/pa <myarena> classchest <myclass>` and items of myclass will be loaded from the chest. If you change chest content, you have to reload the arena.

**Comment by mibby** [comment]
Yes, that is what I am referring to. However it seems reloading the individual arena with ``/pa <arena> reload`` does not refresh any changed class chest contents into memory. The arena seems to cache whatever was loaded initially. If you make any changes to the arena class chest location, you have to ``/pa reload`` to force any changes to refresh and appear. Reloading individually does not seem to refresh it. Otherwise changes will appear the next time the map is played.

i.e. play once, game ends, start same arena again, it finally loads new changes

This is something my testers noticed when making edits to class contents / chest inventory then trying to test the changes by playing in the arena after forcing a specific map reload.

**Comment by Eredrim** [comment]
I can't reproduce it. Here is how I tested it:
- I had 4 classes with 4 associated chests
- I added a random item in two of them
- I typed `/pa <arena> reload`
- Two players gone in the lobby, random items correctly appeared when classes were selected
- Players played an entire game (CTF)
- After the end of the match, random items were removed and new random items were placed instead of them.
- I typed `/pa <arena> reload` (again)
- Two players gone in the lobby, new random items correctly appeared when classes were selected

Works identically if players don't play the arena before changing items.

So, no problem for me...
Can you pass me your config file and describe your reproduction workflow as I've done ?

**Comment by Eredrim** [comment]
@mibby Any news about this ?
