### ISSUE TITLE
Massive Recurring Error in Console

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#38]
Situation: Player joined a Checkpoint arena, then left the game and rejoined.

Error: https://controlc.com/8d929b84
Plugin Version: 1.15.0-SNAPSHOT-b323
Paper version: Paper-264

**Comment by Eredrim** [comment]
Problem is exactly the same you already had in issue #31, exit spawn is missing. I made a fix to block arena while it's not repaired. Maybe you haven't installed it because it's within module files and not directly in the plugin. Just download latest modules pack here : https://ci.craftyn.com/job/PVP%20Arena%20Modules/, extract its content your folder `plugin/pvparena/files`. Then type `/pa update` and restart your server.

**Comment by J-SHarper** [comment]
Ah, understood. Thank you!
